### ISSUE TITLE
Task times are not shown when footer is hidden

### ISSUE THREAD

**Issue by wagoodman** [wagoodman/bashful#14]
I think. Happens with this config:

```
config:
  log-path: build.log
  collapse-on-completion: true
  show-summary-footer: false
  show-task-output: false
  # show-task-times: false

```

I expected the tasks to still be shown.
