### ISSUE TITLE
Allow tasks to reference a URL to a shell script

### ISSUE THREAD

**Issue by wagoodman** [wagoodman/bashful#19]
```yaml
- name: Install NPM
   url: http://npmjs.org/install.sh
```
should be able to take an optional checksum:
```yaml
- name: Install NPM
   url: http://npmjs.org/install.sh
   md5: 9c5d46a77f54bbc3ea1ace3a21b26fa7
```
...and runtime options (? is replaced with the downloaded script):
```yaml
- name: Install NPM
   url: http://npmjs.org/install.sh
   runtime: sudo ? --some options -h here 
```
