### ISSUE TITLE
Being able ask user for command input (Sudo passwords, or others)

### ISSUE THREAD

**Issue by matthieusb** [wagoodman/bashful#37]
Hello,

I have been trying to automate a linux install script. But I can't manage to enter my password when using 'sudo' in my command. IN this case the script hangs and never finished.

See the code below for a yaml example :

```
tasks:
  - name: 'Basic Tools install'
    cmd: sudo apt install -y <replace>
    for-each: *basic-tools-names
```

Would it be possible to add the possibility of entering the input asked for any command ?

Still, this is an awesome project. Thank you for your hard work.
Thanks in advance.

**Comment by amir20** [comment]
Couldn't you just do `sudo bashful run file.yml` instead?

**Comment by klauern** [comment]
One thing I've done with Ansible was to develop a `sudo_action` module that performed the command using a stored variable holding the password.  Since you could export that to an environment variable, it could be something like

```yml
- name: sudo command call
  sudo_cmd: apt install <x>
  sudo_password: $SUDO_PASS_ENV_VAR
```
or somethign similar.  In addition, `sudo` takes a `-S` flag to read the password in stdin:

```
-S, --stdin
            Write the prompt to the standard error and read the password from the standard input instead of using the terminal device.  The password must be followed by a newline character.
```

**Comment by matthieusb** [comment]
@amir20 I could indeed (I just need to export my gopath for root as weel). 
That being said, information other than just the sudo password might be needed for install operations, like when you install apt-cacher or some databases, which ask you a few things directly in the console.

Would there be a generic solution to handle this problem ? Is this tool supposed to do it ?

**Comment by klauern** [comment]
I would think there's something similar to `expect` that could handle that for you, too:

* http://devdocs.io/ansible/expect_module
* http://docs.ansible.com/ansible/latest/expect_module.html
* https://pexpect.readthedocs.io/en/stable/
* And the tool all of the above are inspired by - http://expect.sourceforge.net/

**Comment by wagoodman** [comment]
I like the idea of flagging commands that should be run with sudo and letting bashful determine if it should prompt ahead of time for a password... for instance:
```yaml
- name: sudo command call
  sudo: true
  cmd: apt install <x>
```
in which case simply running `bashful run some.yml` will test for sudo access if any tasks have the `sudo: true` option configured, ask for a password if necessary, store and use the password on the right tasks. This would prevent the need to invoke it with a new cli switch to prompt for sudo. 

Any opinions/thoughts on this approach?
