### ISSUE TITLE
docker pull output 

### ISSUE THREAD

**Issue by matti** [wagoodman/bashful#43]
```
tasks:
  - name: pull
    cmd: docker pull ubuntu:14.10
    show-output: true
```

shows "b0efe5c05b4c: Download complete" as the output, because the last line is not the one that shows the progress:

```
$ docker pull ubuntu:14.10
14.10: Pulling from library/ubuntu
b0efe5c05b4c: Downloading [==================================>                ]  46.83MB/68.32MB
0a1f1b169319: Download complete
1ceb0a3c7c48: Download complete
a3ed95caeb02: Download complete
```

Can this be fixed?
