### ISSUE TITLE
Inclusion of other bashful scripts

### ISSUE THREAD

**Issue by muesli** [wagoodman/bashful#47]
It would be nice if you could include a bashful yaml in another one.

**Comment by wagoodman** [comment]
I'd be up for trying it, my first take would be something like:

```yaml
# commonconfig.yaml

show-failure-report: false
show-summary-errors: true
max-parallel-commands: 6
collapse-on-completion: true
show-task-times: true
```

```yaml
# cleanuptasks.yaml

- name: an external cleanup task
  cmd: echo 'do something useful'
- name: another external clean up task
  cmd: rm -rf something
```

```yaml
# sometasks.yaml

- name: an external task
  cmd: echo 'do something useful'
- name: clean up
  cmd: rm -rf something
```

```yaml
# run.yml
config: $include commonconfig.yaml
tasks:
  - name: do a task
    cmd: echo "hello, task"
  - parallel-tasks:
      - cmd: make build 
      - $include: sometasks.yaml
  - $include: cleanuptasks.yaml
```

which generates:
```yaml
config:
  show-failure-report: false
  show-summary-errors: true
  max-parallel-commands: 6
  collapse-on-completion: true
  show-task-times: true
tasks:
  - name: do a task
    cmd: echo "hello, task"
  - parallel-tasks:
      - cmd: make build 
      - name: an external task
        cmd: echo 'do something useful'
      - name: clean up
        cmd: rm -rf something
  - name: an external cleanup task
    cmd: echo 'do something useful'
  - name: another external clean up task
    cmd: rm -rf something
```

I see a couple problems with the above example, but it's a start. Yaml inherently doesn't support including other files in the spec, so it would have to be a relatively 'simple' mechanism of find-keyword-and-replace-value... with some tailoring of indentation levels.

Anyone seen a better way of expressing this?
