### ISSUE TITLE
Feature request: Including external bash script

### ISSUE THREAD

**Issue by mumoshu** [wagoodman/bashful#49]
Hi, thanks for sharing a great tool!

While trying to author a relatively large tool based on bashful, I came up with this, so that I could write a lengthy bash script on our favorite editor with nice syntax highlighting, lint, etc.

Instead of:

```
tasks:
    - name: Building app
      cmd: go build -ldflags '-linkmode external -extldflags -static -s'
      tags: build
```

I'd like to organize it by extracting the `cmd` to a dedicated bash script:

```
tasks:
    - name: Building app
      script: scripts/build
      tags: build
```

Whereas `scripts/build` is:

```
#!/usr/bin/env bash

set -e
go build -ldflags '-linkmode external -extldflags -static -s'
```

Note that we can't just write it `cmd: ./scripts/build` as it doesn't get bundled in `bashful bundle`.

**Comment by mumoshu** [comment]
Also note that this solves slightly different issue than #47.
#47 solves the problem of separating bashful yamls, whereas this solves separating bashful yaml vs bash scripts embedded in it.

**Comment by wagoodman** [comment]
Actually, the plan is to later add the ability to flag tasks that have assets that need to be included into a bundle (or list them explicitly). Ideally it would be nice to simply extrapolate an asset from the cmds that start with a relative or absolute path to a file, and automatically include them into the bundle. This would prevent the need to add a keyword, which is always good .

**Comment by mumoshu** [comment]
@wagoodman Thanks for the response!

Yeah, no need to add a brand-new keyword would always be good.

However though, how do you determine whether `scripts/something` in `cmd: ./scripts/something` is really intended to be included in the bundle or not?
Both are understandable for me. I'd like the bashful bundle to just call `$(pwd)/scripts/something` instead of the bundled one when my use-case is treating bashful as a framework.

In that regard, I'd prefer listing bundled scripts explicitly. Just my two cents.

**Comment by wagoodman** [comment]
Sorry for the delay! So I decided to go the easy route and went the explicit route for now, that way we can get this functionality in but we haven't closed off the possibility of automatically detecting what to bundle in the future (something like `bundle: auto`). 

Ok, here's an example of what was just added:
```yaml
# run.yaml
config:
  bundle:
    - example/scripts/random-worker.sh
    - example/scripts/compile-something.sh
tasks:
  - name: Compiling source
    parallel-tasks:
      - cmd: example/scripts/random-worker.sh 3
      - cmd: example/scripts/compile-something.sh 2
```

When you bundle with `bashful bundle run.yaml` you get a file `run.bundle` that has the two files included. The temp dir created mimics the relative layout:

```
/tmp/bashful.tkud2d/
├── 16-bundle-manifest.yml
├── example
│   └── scripts
│       ├── compile-something.sh
│       └── random-worker.sh
└── bashful
```

I need to add a few more tests around this before I cut a release with it, but this is what the current functionality looks like. I just pushed it up to master if you wanted to give it a shot. Otherwise I'll update here when the feature is about to be released.
