### ISSUE TITLE
Parallelize for-each

### ISSUE THREAD

**Issue by kwrobert** [wagoodman/bashful#51]
Add a flag to a task block that allows a for-each sweep through parameters to be parallelized across parameter values #

**Comment by wagoodman** [comment]
If I understand correctly, you want to be able to parallelize tasks defined in a `for-each` loop. That can be done like so:
```
tasks:
  - name: Cloning Repos
    parallel-tasks:
      - name: "Cloning <replace>"
        cmd: example/scripts/random-worker.sh 4 <replace>
        for-each:
              - some-lib-4
              - utilities-lib
              - important-lib
```
Is this what you are asking?
