### ISSUE TITLE
Complete footer shows /dev/null for log when not configured

### ISSUE THREAD

**Issue by wagoodman** [wagoodman/bashful#63]
As seen in #62: ...`See log for details (/dev/null) `...

**Comment by alexislefebvre** [comment]
Sorry, I didn't put the whole configuration file in #62.

I was testing `bashful` and I used this configuration to disable logging:

```yaml
config:
    # log all task output and events to the given logfile
    log-path: /dev/null
```

So it looks like it's the expected behaviour to see `See log for details (/dev/null)` in the output.
