### ISSUE TITLE
Crashes with lots of small file -- too many open files

### ISSUE THREAD

**Issue by drmikecrowe** [wagoodman/bashful#66]
Trying to run a bunch of small tasks in parallel (trying 12x once)

Error:

```
Line: 193 ash /hFile: /home/wagoodman/go/src/github.com/wagoodman/bashful/screen.go s/leftcenter/the-forward/the-forward-all.html                                                                                  
 fork/exec /bin/stty: too many open files                                                                                                                                          Runtime[00:01:22] ETA[00:-1:-22]
&{0xc4200a0060} Unable to determine screen width.
```

yml file is built from a list:

```yml
config:
    max-parallel-commands: 12
tasks:

  - name: Download 1 of 227
    parallel-tasks:
      - cmd: bash inner-find-domain.sh [a local path]
      - cmd: bash inner-find-domain.sh [a local path]
      - cmd: bash inner-find-domain.sh [a local path]
      - cmd: bash inner-find-domain.sh [a local path]
      - cmd: bash inner-find-domain.sh [a local path]
      - cmd: bash inner-find-domain.sh [a local path]
      - cmd: bash inner-find-domain.sh [a local path]
      - cmd: bash inner-find-domain.sh [a local path]
      - cmd: bash inner-find-domain.sh [a local path]
      - cmd: bash inner-find-domain.sh [a local path]
      - cmd: bash inner-find-domain.sh [a local path]
      - cmd: bash inner-find-domain.sh [a local path]

  - name: Download 2 of 227
    parallel-tasks:
      - cmd: bash inner-find-domain.sh [a local path]
      - cmd: bash inner-find-domain.sh [a local path]
      - cmd: bash inner-find-domain.sh [a local path]
      - cmd: bash inner-find-domain.sh [a local path]
      - cmd: bash inner-find-domain.sh [a local path]
      - cmd: bash inner-find-domain.sh [a local path]
      - cmd: bash inner-find-domain.sh [a local path]
      - cmd: bash inner-find-domain.sh [a local path]
      - cmd: bash inner-find-domain.sh [a local path]
      - cmd: bash inner-find-domain.sh [a local path]
      - cmd: bash inner-find-domain.sh [a local path]
      - cmd: bash inner-find-domain.sh [a local path]
```
