### ISSUE TITLE
Performance does not scale well for several parallel tasks

### ISSUE THREAD

**Issue by wagoodman** [wagoodman/bashful#67]
This takes several seconds to run:
```
config:
#  log-path: build.log
  max-parallel-commands: 12
  event-driven: false
tasks:
  - name: Processing
    parallel-tasks:
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test
    - cmd: echo test


```
